apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-refiner
  namespace: $(NAMESPACE_NODE_REFINER)
  labels:
    app: node-refiner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-refiner
  template:
    metadata:
      labels:
        app: node-refiner
    spec:
      serviceAccountName: node-refiner-sa
      imagePullSecrets:
        - name: nr-docker-registry
      containers:
        - name: node-refiner
          image: ghcr.io/sap/node-refiner:0.0.7
          imagePullPolicy: Always
          ports:
            - name: health
              containerPort: 9102
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              port: health
          env:
            - name: LISTENING_PORT
              value: "8080"
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
