apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: node-refiner
resources:
  - namespace.yaml
  - service.yaml
  - crb.yaml
  - deployment.yaml
  - settings.yaml
  - env/env.deploy.vars.yaml

configurations:
  - kustomizeconfig/rolebinding.yaml
  - kustomizeconfig/namespace.yaml

vars:
  - fieldref:
      fieldpath: data.NAMESPACE_NODE_REFINER
    name: NAMESPACE_NODE_REFINER
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: deployment-variables

images:
  - name: default
    newName: ghcr.io/sap/node-refiner
    newTag: latest