apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: $(NAMESPACE_NODE_HARVESTER)
  annotations:
    replicator.v1.mittwald.de/replicate-from: cluster-secrets/docker-registry
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  .dockercfg: e30K
type: kubernetes.io/dockercfg