apiVersion: v1
kind: ConfigMap
metadata:
  name: node-harvester-cm
  namespace: $(NAMESPACE_NODE_HARVESTER)
data:
  drainer_enabled: "true"
  time_gap: "5"
  time_since_last_addition: "30"
  minimum_nodes: "3"
  minimum_non_tainted_nodes: "3"
  excess_nodes_threshold: "2"

