apiVersion: v1
kind: ConfigMap
metadata:
  name: node-refiner-cm
  namespace: $(NAMESPACE_NODE_REFINER)
data:
  drainer_enabled: "false"
  time_gap: "5"
  time_since_last_addition: "60"
  minimum_nodes: "3"
  minimum_non_tainted_nodes: "3"
  excess_nodes_threshold: "2"

