{
 "title": "Node Harvester Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Drainer Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Cordoned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_harvester_nodes_cordoned[30d]))",
     "legendFormat": "Nodes Cordoned"
    },
    {
     "expr": "sum(increase(node_harvester_nodes_drained[30d]))",
     "legendFormat": "Nodes Drained"
    },
    {
     "expr": "sum(increase(node_harvester_nodes_uncordoned[30d]))",
     "legendFormat": "Nodes Uncordoned"
    }
   ]
  },
  {
   "title": "Unschedulable Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_unschedulable_nodes)",
     "legendFormat": "Unschedulable Nodes"
    }
   ]
  },
  { "title": "Cluster State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "# Cluster State\n\nMetrics on the overall status of the cluster, these metrics aggregate the relevant information in order to give a hollistic overview.\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_cpu_utilization)"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_memory_utilization)"
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "graph",
   "description": "Percentage of CPU Utilization",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_cpu_utilization)",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(node_harvester_cluster_memory_utilization)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_nodes)"
    }
   ]
  },
  {
   "title": "Number of Non Tainted Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_non_tainted_nodes)"
    }
   ]
  },
  {
   "title": "Number of Tainted Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_nodes - node_harvester_cluster_non_tainted_nodes)"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_pods)"
    }
   ]
  },
  {
   "title": "Current Excess Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_excess_nodes)"
    }
   ]
  },
  {
   "title": "Cluster Nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_nodes)",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "sum(node_harvester_cluster_non_tainted_nodes)",
     "legendFormat": "Non Tainted Nodes"
    },
    {
     "expr": "sum(node_harvester_cluster_nodes) - sum(node_harvester_cluster_non_tainted_nodes)",
     "legendFormat": "Tainted Nodes"
    }
   ]
  },
  {
   "title": "Excess Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_excess_nodes)"
    }
   ]
  },
  {
   "title": "Delta Nodes",
   "type": "graph",
   "description": "Visualizing the change in the number of nodes across time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(node_harvester_cluster_nodes[$__rate_interval]))",
     "legendFormat": "Change in Total Nodes"
    },
    {
     "expr": "sum(delta(node_harvester_cluster_non_tainted_nodes[$__rate_interval]))",
     "legendFormat": "Change in Non Tainted Nodes"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_harvester_cluster_pods)"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{app=\"node-harvester\"}"
    }
   ]
  }
 ]
}